version: '3.12'

services:
  web:
    build: .
    command: fastapi run main.py --port 80
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/foo
    volumes:
      - .:/app
    ports:
      - 80:80
    depends_on:
      - postgres

  postgres:
    image: postgres:16.4
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo

  redis:
    image: redis

  worker:
    build: .
    command: celery -A worker.app worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./project:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis